workers/openrelik-worker-analyzer-config: 'workers/openrelik-worker-analyzer-config/**'
workers/openrelik-worker-analyzer-logs: 'workers/openrelik-worker-analyzer-logs/**'
workers/openrelik-worker-bulkextractor: 'workers/openrelik-worker-bulkextractor/**'
workers/openrelik-worker-capa: 'workers/openrelik-worker-capa/**'
workers/openrelik-worker-containers: 'workers/openrelik-worker-containers/**'
workers/openrelik-worker-cloud-logs: 'workers/openrelik-worker-cloud-logs/**'
workers/openrelik-worker-dfindexeddb: 'workers/openrelik-worker-dfindexeddb/**'
workers/openrelik-worker-duckdb: 'workers/openrelik-worker-duckdb/**'
workers/openrelik-worker-extraction: 'workers/openrelik-worker-extraction/**'
workers/openrelik-worker-floss: 'workers/openrelik-worker-floss/**'
workers/openrelik-worker-os-creds: 'workers/openrelik-worker-os-creds/**'
workers/openrelik-worker-strings: 'workers/openrelik-worker-strings/**'
workers/openrelik-worker-yara: 'workers/openrelik-worker-yara/**'